Repository DeveloperAcademy-POSTECH/PickBus, pull requests merged in 2022-11, with the labels that each got.

#3 PR 탬플릿 추가
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, chore

#6 [chore] Add auto-assign
  .github/auto_assign.yml
Labels: chore

#20 HTTP set up and protect key file
  .gitignore
  WidgetBus/Info.plist
Labels: chore

#22 Change lint identifier length 4 to 3
  .swiftlint.yml
Labels: chore

#24 Add color set
  WidgetBus/Assets.xcassets/DuduBlue.colorset/Contents.json
  WidgetBus/Assets.xcassets/DuduRed.colorset/Contents.json
  WidgetBus/Assets.xcassets/DuduYellow.colorset/Contents.json
  WidgetBus/Assets.xcassets/duduDeepBlue.colorset/Contents.json
  WidgetBus/Assets.xcassets/duduGray.colorset/Contents.json
Labels: chore

#26 Create select route number view
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Base.lproj/Main.storyboard
  WidgetBus/Models/Network/ArriveInfoFromBusStop.swift
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Views/SelectRouteNumberView/RouteNumberViewStoryboard.storyboard
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: feature

#29 Create RouteDetailView UI
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Views/RouteDetailView/RouteDetailTableViewCell.swift
  WidgetBus/Views/RouteDetailView/RouteDetailView.storyboard
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: feature

#32 fix error
  WidgetBus.xcodeproj/xcshareddata/xcschemes/WidgetBus.xcscheme
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: bug

#18 Make routelistview UI
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/ColorSet/AccentColor.colorset/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/duduBlue.colorset/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/duduDeepBlue.colorset/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/duduGray.colorset/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/duduRed.colorset/Contents.json
  WidgetBus/Assets.xcassets/ColorSet/duduYellow.colorset/Contents.json
  WidgetBus/Extensions/NSObject+.swift
  WidgetBus/Extensions/UIColor+.swift
  WidgetBus/SceneDelegate.swift
  WidgetBus/Views/RouteListView/AddRouteTableViewCell.swift
  WidgetBus/Views/RouteListView/BusData.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
  WidgetBus/Views/RouteListView/RouteTableFooter.swift
  WidgetBus/Views/RouteListView/RouteTableHeader.swift
  WidgetBus/Views/RouteListView/RouteTableViewCell.swift
Labels: feature

#35 Get All Nodes by route number from API.
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Base.lproj/Main.storyboard
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/BusLocationFromBusStop.swift
  WidgetBus/Models/Network/RouteNodes.swift
  WidgetBus/SceneDelegate.swift
  WidgetBus/Views/RouteDetailView/RouteDetailView.storyboard
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: feature

#36 RouteDetailView with Network function
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Models/Network/ArriveInfoFromBusStop.swift
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/BusLocationsOnRoute.swift
  WidgetBus/Models/Network/RouteInformation.swift
  WidgetBus/Models/Network/RouteNodes.swift
  WidgetBus/Models/Network/SpecificArrive.swift
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: feature

#41 Apply Search Function to SelectStartStationView
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/CityCode.swift
  WidgetBus/Models/Network/MySearchNodeInfo.swift
  WidgetBus/Models/Network/SearchNode.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature

#37 RouteListView UI
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/duduPlus.imageset/Contents.json
  WidgetBus/Assets.xcassets/duduPlus.imageset/Plus.png
  WidgetBus/ViewController.swift
  WidgetBus/Views/RouteListView/AddRouteCell.swift
  WidgetBus/Views/RouteListView/BusStopCell.swift
  WidgetBus/Views/RouteListView/RouteCell.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
  WidgetBus/Views/RouteListView/RouteTableFooter.swift
  WidgetBus/Views/RouteListView/TitleHeader.swift
Labels: feature

#42 Make SelectArrivalView
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/progressIndicator4.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator4.imageset/ProgressIndicator4.png
  WidgetBus/Base.lproj/Main.storyboard
  WidgetBus/Models/ArrivalNodeModel.swift
  WidgetBus/ViewController.swift
  WidgetBus/Views/SelectArrivalView/ArrivalTableViewCell.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
Labels: feature

#43 GroupListView UI
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/AppDelegate.swift
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/Contents.json
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/ProgressIndicator.png
  WidgetBus/Base.lproj/LaunchScreen.storyboard
  WidgetBus/Info.plist
  WidgetBus/SceneDelegate.swift
  WidgetBus/Views/GroupListView/AddGroupListNameView.swift
  WidgetBus/Views/GroupListView/AddGroupTableViewCell.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/GroupListView/GroupTableViewCell.swift
  WidgetBus/Views/GroupListView/SettingViewController.swift
Labels: feature

#45 Revert "GroupListView UI"
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/AppDelegate.swift
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/Contents.json
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/ProgressIndicator.png
  WidgetBus/Base.lproj/LaunchScreen.storyboard
  WidgetBus/Info.plist
  WidgetBus/SceneDelegate.swift
  WidgetBus/Views/GroupListView/AddGroupListNameView.swift
  WidgetBus/Views/GroupListView/AddGroupTableViewCell.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/GroupListView/GroupTableViewCell.swift
  WidgetBus/Views/GroupListView/SettingViewController.swift
Labels: bug, chore

#39 Make a CoreData
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/AppDelegate.swift
  WidgetBus/Models/CoreData/BusCoreDataModel.xcdatamodeld/BusCoreDataModel.xcdatamodel/contents
  WidgetBus/Models/CoreData/DataController.swift
Labels: feature

#46 Fix marge conflict GroupListView UI
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/Contents.json
  WidgetBus/Assets.xcassets/ProgressIndicator.imageset/ProgressIndicator.png
  WidgetBus/Views/GroupListView/AddGroupListNameView.swift
  WidgetBus/Views/GroupListView/AddGroupTableViewCell.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/GroupListView/GroupTableViewCell.swift
  WidgetBus/Views/GroupListView/SettingViewController.swift
Labels: bug, chore

#17 Make SelectStartNodeView
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Base.lproj/Main.storyboard
  WidgetBus/Extensions/UITextField+.swift
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/CityCode.swift
  WidgetBus/Models/Network/MySearchNodeInfo.swift
  WidgetBus/Models/Network/SearchNode.swift
  WidgetBus/ViewController.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.xib
Labels: feature

#50 Change table view cell font
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.xib
Labels: feature

#54 Add Backgroundiew
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/progressIndicator1.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator1.imageset/progressIndicator1.png
  WidgetBus/Assets.xcassets/progressIndicator2.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator2.imageset/progressIndicator2.png
  WidgetBus/Assets.xcassets/progressIndicator3.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator3.imageset/progressIndicator3.png
  WidgetBus/Assets.xcassets/progressIndicator_default.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator_default.imageset/progressIndicator_default.png
  WidgetBus/Views/BackgroundViewController.swift
Labels: refactor

#55 Feat/select start node view
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.xib
Labels: feature

#56 Connect view and coredata
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/AppDelegate.swift
  WidgetBus/Base.lproj/Main.storyboard
  WidgetBus/Models/CoreData/BusCoreDataModel.xcdatamodeld/BusCoreDataModel.xcdatamodel/contents
  WidgetBus/Models/Network/ArriveInfoFromBusStop.swift
  WidgetBus/Models/Network/ArriveInfoMultiTypes.swift
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/BusLocationsOnRoute.swift
  WidgetBus/Models/Network/RouteNodes.swift
  WidgetBus/Models/Network/SearchNode.swift
  WidgetBus/Models/Network/StringMultiType.swift
  WidgetBus/SceneDelegate.swift
  WidgetBus/Views/GroupListView/AddGroupListNameView.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature

#58 Change API
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Models/Network/AllRoutesFromNode.swift
  WidgetBus/Models/Network/BusClient.swift
  WidgetBus/Models/Network/MyAllRoutesFromNodeMultiType.swift
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: feature

#59 background view update
  WidgetBus/Views/BackgroundViewController.swift
Labels: refactor
