Repository DeveloperAcademy-POSTECH/PickBus, pull requests merged in 2022-12, with the labels that each got.

#62 Connect BackgroundViewController to use navigation bar in SelectStartNodeView
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature, refactor

#64 Feat Update multiple bus at one stop, Update bus boarding state
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Info.plist
  WidgetBus/Views/RouteDetailView/RouteDetailTableViewCell.swift
  WidgetBus/Views/RouteDetailView/RouteDetailView.storyboard
  WidgetBus/Views/RouteDetailView/RouteDetailViewController-+CLLocationManagerDelegate.swift
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: feature

#72 Fix location error
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: bug

#67 Refactor RouteListView
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/RouteListView/AddRouteCell.swift
  WidgetBus/Views/RouteListView/BusData.swift
  WidgetBus/Views/RouteListView/BusStopCell.swift
  WidgetBus/Views/RouteListView/RouteCell.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
  WidgetBus/Views/RouteListView/TitleHeader.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
Labels: feature

#68 Feat/route number background and refector some view
  WidgetBus/Models/Network/RouteNodes.swift
  WidgetBus/Views/SelectRouteNumberView/RouteNumberViewStoryboard.storyboard
  WidgetBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: feature

#73 Add alert in routeDetailView
  WidgetBus/Views/RouteDetailView/RouteDetailViewController-+CLLocationManagerDelegate.swift
  WidgetBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: feature

#71 API link in selectStartNodeView
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Models/StartNodeModel.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.swift
  WidgetBus/Views/SelectStartNodeView/TableViewCell/SelectStartNodeTableViewCell.xib
Labels: feature

#52 refactor SelectArrivalViewController
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/Assets.xcassets/progressIndicator1of3.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator1of3.imageset/progressIndicator1of3.png
  WidgetBus/Assets.xcassets/progressIndicator2of3.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator2of3.imageset/progressIndicator2of3.png
  WidgetBus/Assets.xcassets/progressIndicator3of3.imageset/Contents.json
  WidgetBus/Assets.xcassets/progressIndicator3of3.imageset/progressIndicator3of3.png
  WidgetBus/ViewController.swift
  WidgetBus/Views/BackgroundViewController.swift
  WidgetBus/Views/SelectArrivalView/ArrivalTableViewCell.swift
  WidgetBus/Views/SelectArrivalView/BusBadgeView.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
Labels: refactor

#79 Fix GroupListView
  WidgetBus/Assets.xcassets/AppIcon.appiconset/100.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/1024.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/114.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/120.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/128.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/144.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/152.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/16.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/167.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/172.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/180.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/196.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/20.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/216.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/256.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/29.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/32.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/40.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/48.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/50.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/512.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/55.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/57.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/58.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/60.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/64.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/66.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/72.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/76.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/80.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/87.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/88.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/92.png
  WidgetBus/Assets.xcassets/AppIcon.appiconset/Contents.json
  WidgetBus/Views/GroupListView/AddGroupListNameView.swift
  WidgetBus/Views/GroupListView/AddGroupTableViewCell.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/GroupListView/GroupTableViewCell.swift
  WidgetBus/Views/GroupListView/SettingViewController.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: bug

#78 [fix] move to RootView
  WidgetBus/Views/RouteListView/RouteCell.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
Labels: bug

#77 Connect selected start node api data with coredata
  WidgetBus/Models/StartNodeModel.swift
  WidgetBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature

#76 Add custom transition animation
  WidgetBus.xcodeproj/project.pbxproj
  WidgetBus/CustomAnimation/ExtendFromCellTransition.swift
  WidgetBus/CustomAnimation/ShrinkToCellTransition.swift
  WidgetBus/CustomAnimation/TransitInfoProtocol.swift
  WidgetBus/Views/GroupListView/GroupListViewContoller.swift
  WidgetBus/Views/RouteListView/RouteListViewController.swift
  WidgetBus/Views/SelectArrivalView/SelectArrivalViewController.swift
Labels: feature

#86 core data fix
  PickBus.xcodeproj/project.pbxproj
  PickBus/Models/Network/BusClient.swift
  PickBus/Models/Network/BusLocationInfoMultiType.swift
  PickBus/Models/Network/BusLocationsOnRoute.swift
  PickBus/Models/Network/RouteInformation.swift
  PickBus/Models/Network/RouteNodes.swift
  PickBus/Views/GroupListView/AddGroupListNameView.swift
  PickBus/Views/GroupListView/GroupListViewContoller.swift
  PickBus/Views/RouteDetailView/RouteDetailView.storyboard
  PickBus/Views/RouteDetailView/RouteDetailViewController.swift
  PickBus/Views/RouteListView/RouteListViewController.swift
  PickBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
  PickBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature

#87 [bug] Fix group list view coredata ascending
  PickBus/Views/GroupListView/GroupListViewContoller.swift
  PickBus/Views/GroupListView/SettingViewController.swift
  PickBus/Views/RouteDetailView/RouteDetailViewController-+CLLocationManagerDelegate.swift
  PickBus/Views/RouteDetailView/RouteDetailViewController.swift
  PickBus/Views/RouteListView/RouteListViewController.swift
  PickBus/Views/SelectArrivalView/SelectArrivalViewController.swift
  PickBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
Labels: bug, refactor

#89 Core data duplicate
  PickBus/Models/Network/BusClient.swift
  PickBus/Views/GroupListView/AddGroupListNameView.swift
  PickBus/Views/RouteDetailView/RouteDetailViewController.swift
  PickBus/Views/SelectArrivalView/SelectArrivalViewController.swift
  PickBus/Views/SelectRouteNumberView/SelectRouteNumberViewController.swift
  PickBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: feature

#90 Fix Routelistview
  PickBus/Views/RouteListView/RouteCell.swift
  PickBus/Views/RouteListView/RouteListViewController.swift
Labels: bug

#91 Update routeDetailView
  PickBus.xcodeproj/project.pbxproj
  PickBus/Assets.xcassets/Image/bus/Bus2.imageset/Bus2.png
  PickBus/Assets.xcassets/Image/bus/Bus2.imageset/Bus2@2x.png
  PickBus/Assets.xcassets/Image/bus/Bus2.imageset/Bus2@3x.png
  PickBus/Assets.xcassets/Image/turnover.imageset/Contents.json
  PickBus/Assets.xcassets/Image/turnover.imageset/turnOver@2x.png
  PickBus/Assets.xcassets/Image/turnover.imageset/turnOver@3x.png
  PickBus/Assets.xcassets/Image/turnover.imageset/turnover.png
  PickBus/Models/Network/BusClient.swift
  PickBus/Models/Network/MySpecificArriveInfoMultiType.swift
  PickBus/Models/Network/RouteInformation.swift
  PickBus/Models/Network/SpecificArrive.swift
  PickBus/Views/RouteDetailView/RouteDetailView.storyboard
  PickBus/Views/RouteDetailView/RouteDetailViewController.swift
Labels: feature

#92 Feat/select start node view
  PickBus.xcodeproj/project.pbxproj
  PickBus/Assets.xcassets/Image/turnover.imageset/Contents.json
  PickBus/Views/SelectStartNodeView/SelectStartNodeView.storyboard
  PickBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: bug, feature

#93 [bug] Fix distance doesnt work issue
  PickBus/Views/SelectStartNodeView/SelectStartNodeViewController.swift
Labels: bug
